# Default values for lightning-terminal-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/lightninglabs/lightning-terminal
  pullPolicy: IfNotPresent
  tag: "v0.6.1-alpha-path-prefix"

podAnnotations: {}

livenessProbe:
  enabled: false
  path: "/"

readinessProbe:
  enabled: false
  path: "/"

secrets:
  certificates:
    path: "/data/.lnd"
    enable: true
    secretName: {}
  ui:
    password: $3kr3tP4zW0rd
  env:
    enable: true
    secretName: secrets-env

service:
  type: ClusterIP
  port: 3000

network: 'testnet'
lit:
  dir: ~/.lit
  additionalConfig: ''
serverUrl: {}

https:
  enabled: false
  letsencrypt: false
  letsencrypthost: {}
  httpslisten:
    url: '0.0.0.0'
    port: 8443

nodeSelector: {}

tolerations: []

affinity: {}
